### ISSUE TITLE
Author和Win下实际创建文件名的一点异常处理

### ISSUE THREAD

**Issue by blkot** [benny502/varman#1]
Zod来的，牛逼

不懂go，不过简单读了一下，还差一点点。
对于极少数var包的author（其实到现在五百G就遇到一个文件，jj builds .jjcruise.1.var）
这个命名极其不负责任，author末尾是一个空格，而在win下文件夹名会自动Trim掉末尾的空格，导致移动的时候会找不到目标位置

处理方式就不用我说了

**Comment by benny502** [comment]
谢谢提醒，已经修复了
